eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost


microservice:
  order-service:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/orders/createOrder
  payment-service:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/payment/doPayment
  identity-service:
    endpoints:
      endpoint:
        uri: http://IDENTITY-SERVICE/auth/
        
       



